### ISSUE TITLE
Wrong syntax for Yandex

### ISSUE THREAD

**Issue by Korb** [dessant/web-archives#55] opened 2022-08-15 13:11 UTC
**System**

* OS name: Microsoft Windows
* OS version: 10.0.19043.1889
* Browser name: Mozilla Firefox
* Browser version: 104.0b9 (64-bit)
* Extension version: 3.1.0 (15 August 2022)

**Bug description**
A request to the Yandex cache using the add-on displays the main page of this search engine, and not the cached web page. For example, https://github.com/dessant/web-archives should display [this web page](https://yandexwebcache.net/yandbtm?fmode=inject&tm=1660568568&tld=ru&lang=en&la=1659966720&text=https%3A%2F%2Fgithub.com%2Fdessant%2Fweb-archives&url=https%3A%2F%2Fgithub.com%2Fdessant%2Fweb-archives&l10n=ru&mime=html&sign=4a8e4c6aae3f0d7dbd90f3520a4b6d86&keyno=0).

![2022-08-15_16-10-40](https://user-images.githubusercontent.com/3509797/184641158-6dc3cbe7-ff55-4a15-b439-a20ce47d9363.png)

**Logs**
```
16:07:38.636 Layout was forced before the page was fully loaded. If stylesheets are not yet loaded this may cause a flash of unstyled content. yandex.ru:33:1660
16:07:38.650 <unavailable> content.js:1064:15
16:07:38.742 Found existing Ya object: <unavailable> RU AdList JS Fixes.user.js:5143:42
16:07:38.758 Active cookies: yandexuid=3304095571654971210; yp=1970331218.udn.cDpQaGlsbGlwcGEgTWFja2F5#1676334840.szm.1:1920x1200:1669x1087#1660570311.rnwcst.3#1663158811.ygu.1#1660655258.com.3; L=eX10dAtiUn5BRX5hVgJDAmEFDV4DXF1fESYhe1IJMX8CO0EvAAA=.1654971218.15005.316499.ee1fea527e0c980936eb97c7fd579a36; yandex_login=ALE-aka-Korwin; instruction=1; is_gdpr=0; is_gdpr_b=CN/1QxCEeigC; _yasc=5N5MNcpcqST0/y9BfROoeAZ0MQe4K2B/drlcNdukiS3+hFCpBt93ZSJDQ0rET4cCN4uRmA==; gdpr=0; _ym_uid=1655561906728654766; yuidss=3304095571654971210; ymex=1970921906.yrts.1655561906; maps_routes_travel_mode=pedestrian; ys=udn.cDpQaGlsbGlwcGEgTWFja2F5#wprid.1660568548569854-17903450442418467443-sas2-0340-sas-l7-balancer-8080-BAL-2136; mda=0; yandex_gid=2; font_loaded=YSv1; my=YwA= RU AdList JS Fixes.user.js:1904:22
16:07:38.863 InstallTrigger is deprecated and will be removed in the future. yandex.ru:28:88
16:07:38.894 home = <unavailable> RU AdList JS Fixes.user.js:5266:38
16:07:38.906 Active cookies: yandexuid=3304095571654971210; yp=1970331218.udn.cDpQaGlsbGlwcGEgTWFja2F5#1676334840.szm.1:1920x1200:1669x1087#1660570311.rnwcst.3#1663158811.ygu.1#1660655258.com.3; L=eX10dAtiUn5BRX5hVgJDAmEFDV4DXF1fESYhe1IJMX8CO0EvAAA=.1654971218.15005.316499.ee1fea527e0c980936eb97c7fd579a36; yandex_login=ALE-aka-Korwin; instruction=1; is_gdpr=0; is_gdpr_b=CN/1QxCEeigC; _yasc=5N5MNcpcqST0/y9BfROoeAZ0MQe4K2B/drlcNdukiS3+hFCpBt93ZSJDQ0rET4cCN4uRmA==; gdpr=0; _ym_uid=1655561906728654766; yuidss=3304095571654971210; ymex=1970921906.yrts.1655561906; maps_routes_travel_mode=pedestrian; ys=udn.cDpQaGlsbGlwcGEgTWFja2F5#wprid.1660568548569854-17903450442418467443-sas2-0340-sas-l7-balancer-8080-BAL-2136; mda=0; yandex_gid=2; font_loaded=YSv1; my=YwA= RU AdList JS Fixes.user.js:1904:22
16:07:39.109
Some cookies are misusing the recommended “SameSite“ attribute 6
16:07:39.109 Cookie “ys_fp” has been rejected because it is already expired. yandex.ru
16:07:39.109 Cookie “maps_routes_travel_mode” has been rejected because it is already expired. yandex.ru
16:07:39.246 Hid banner. RU AdList JS Fixes.user.js:5376:54
16:07:39.517 Ignoring unsupported entryTypes: layout-shift. iD6t7LkKWWL_M8RwrZABpkRiI.js:20:177762
16:07:39.517 Ignoring unsupported entryTypes: largest-contentful-paint. iD6t7LkKWWL_M8RwrZABpkRiI.js:20:178331
16:07:39.545 BODY <unavailable> RU AdList JS Fixes.user.js:5435:58
16:07:39.913 Loading failed for the <script> with source “https://mc.yandex.ru/metrika/watch_serp.js”. yandex.ru:1:1
16:07:39.913 Loading failed for the <script> with source “https://mc.yandex.ru/metrika/tag.js”. yandex.ru:1:1
16:07:39.952 This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. yandex.ru
16:07:41.475 [ClearURLs]: Save on disk. storage.js:84:13
16:07:41.727 Loading failed for the <script> with source “https://mc.yandex.ru/metrika/tag.js”. yandex.ru:1:1
16:07:41.734 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://yabs.yandex.ru/count/WIyejI_zO6i0BGa0L0yVRi_YIdv_FmK0Qm4n6aNwOW00000useqKy0B2xBZH2F050Q061Ca6Iezlf6g1sYsf1vxKUFNNXpn1i0U0W9WygWiGBUGqkvxK003MVEjGH-R0W82029WEofw-ewgjeEqj-10TW14Tg170X3tf4hge_7qc2vUjy18TY1C2y1N1YlRieu-y_6Fu5G795l0_WHUe5mdG627u6EBQa-2-fVAFL80Pa1a1i1cu6V___m7I6H9vOM9pNtDbSdPbSYzoDp0pBJBe6O320_0PWC83c1hnmBG1i1jWk1i4WXmDTLf1EafZObL6HbXYD-aSW1t_Vz0X____0Gu0h46ao1ZuGKxbZgOmvRMgs1QIkH73EbLgPnBcKQ0NPXruD04EsZaBa8WEsWm0~1=WPWejI_zOEC0TGm0j1ND6vSeum503aW2ODmCSE2Fmyl7rjhCom6G0RIksDdKW8200fW1jAxOsLIu0QgRWgeZs06s_-2U0UW1C903yCE0Rw03Ch030gW61Aa7djHuzTU7F46m1u20c3ou1wmqyGS008080GZm2F37uUMZgwtcPUW9Gydu2e2r6DaBw0oJe0x0X3so3mau0KM0KG40I0604Dlzs1_840Ye4S24FTWIWO0OwHAwgFnz9WkNhPWJ1AWJhg_hqOMPx_mMo1G2w1I40f0MvmE15vWNeFNHBS0Nj9O1e1W4i1ZAsEYN1lWOujgJuBwbyezKW1d1YlRieu-y_6EG6G6W6GIu6Vy1w1c0mWFm6O320u4Q___Red0TE4-O6l70j06u6W7r6W40002m6s2u6mJf703mFu0T_t-P7G3mFyWTm8Gzg1u1s1xzZH-W7zlzs1-m7nh87zk_i4
16:07:44.774 Loading failed for the <script> with source “https://mc.yandex.ru/metrika/tag.js”. yandex.ru:1:1
16:07:45.224 Content Security Policy: Ignoring "'unsafe-inline'" within script-src or style-src: nonce-source or hash-source specified
```

**Comment by dessant** [comment] 2022-08-15 13:20
The extension searches with the URL of the active tab and navigates to the first available cached search result. Visiting https://github.com/dessant/web-archives and then clicking on Yandex loads the cached version of the page on my part.

**Comment by Korb** [comment] 2022-08-15 13:32
But not like that:
![2022-08-15_16-31-45](https://user-images.githubusercontent.com/3509797/184644818-7e9b9d5e-a899-4a82-86a0-3efead1ddeac.png)

**Comment by dessant** [comment] 2022-08-15 13:34
You mean when you search the current issue you just opened? Please be specific which URL you search for, and create a screenshot of the end result.

**Comment by Korb** [comment] 2022-08-20 10:12
> Please be specific which URL you search for, and create a screenshot of the end result.

https://addons.mozilla.org/en-US/firefox/addon/view-page-archive/
![Web Archives and Yandex](https://user-images.githubusercontent.com/3509797/185741166-fe6256f3-821b-44a5-b89c-fcbb2ea246ec.gif)

**Comment by dessant** [comment] 2022-08-20 10:29
It looks like You're being redirected to https://yandex.ru because of your geographical location, and Yandex is A/B testing a change on the page that breaks the extension.

I have modified the extension to use https://yandex.ru for testing, and the search form is sucessfully submitted after the https://yandex.ru page loads.

Yandex has probably deployed this change only to some users, so we currently have no way to reproduce the bug. When that page loads, you should wait a minute, and an error notification should show up. After the error shows up, please open the developer tools and look at the page console, and error should be logged there.

**Comment by dessant** [comment] 2022-08-20 10:31
It's also possible that other extensions are interfering, so you could also disable any other extension before testing again.

**Comment by Korb** [comment] 2022-08-20 11:55
> It's also possible that other extensions are interfering, so you could also disable any other extension before testing again.

You are right, it turned out to be the [Containerise](https://addons.mozilla.org/en-GB/firefox/addon/containerise/) add-on. In its settings, Github and Yandex sites are ordered to open in different containers. Apparently, this breaks the functionality of your add-on.

**Comment by alexolog** [comment] 2022-12-27 19:50
Yandex does not work for me as well, it just opens a Yandex search with the url as the search term

**Comment by dessant** [comment] 2023-02-01 19:25
Fixed in https://github.com/dessant/web-archives/commit/88734f654116fcd144c82a652059d2ca0fb1c9b2.

**Closed by dessant** 2023-02-01 19:25 UTC
